# Generated by Django 3.0.5 on 2020-09-19 23:14

import anon.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=25)),
                ('subject', models.CharField(help_text='Name of the sender', max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='senders_view',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='archives',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='likes',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Letters, digits and underscore only.', max_length=30, unique=True, validators=[anon.models.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveIntegerField()),
                ('anon_user_id', models.TextField()),
                ('telegram_switch', models.BooleanField(blank=True, default=False)),
                ('telegram_choice', models.CharField(blank=True, default='3', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
