# Generated by Django 3.0.5 on 2020-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0002_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='device',
            field=models.TextField(default='Fucks'),
        ),
    ]
