# Generated by Django 3.0.5 on 2020-12-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0003_messages_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='anon_user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='anon_user_id',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
