# Generated by Django 3.0.5 on 2021-05-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0004_auto_20201229_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='ip_address',
        ),
    ]
