# Generated by Django 3.0.5 on 2020-09-09 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0004_auto_20200909_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='archives',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 48, 21, 728290)),
        ),
    ]
