# Generated by Django 3.0.5 on 2021-05-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0006_messages_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='ip_address',
        ),
    ]
