# Generated by Django 3.0.5 on 2020-09-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0006_auto_20200909_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='archives',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 51, 21, 198170)),
        ),
    ]
