# Generated by Django 3.0.5 on 2020-09-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0007_auto_20200909_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 51, 37, 154921)),
        ),
    ]
