# Generated by Django 3.2.6 on 2022-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0010_auto_20220328_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='telegram_id',
            field=models.TextField(default='0'),
        ),
    ]
