# Generated by Django 3.0.5 on 2022-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0011_alter_telegram_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='device',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ip_address',
            field=models.GenericIPAddressField(default='Unknown'),
        ),
    ]
