# Generated by Django 3.0.5 on 2022-04-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0012_auto_20220401_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterField(
            model_name='messages',
            name='device',
            field=models.TextField(default='Unknown', editable=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ip_address',
            field=models.GenericIPAddressField(default='Unknown', editable=False),
        ),
    ]
