# Generated by Django 3.0.5 on 2020-09-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0012_auto_20200909_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 18, 1, 1, 406914)),
        ),
    ]
