# Generated by Django 3.0.5 on 2022-04-04 20:25

import anon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0013_auto_20220401_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='archives',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='likes',
            new_name='liked',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='telegram_choice',
        ),
        migrations.AddField(
            model_name='telegram',
            name='amount_of_messages_to_send',
            field=models.PositiveIntegerField(blank=True, default=3, validators=[anon.models.max_value_validator]),
        ),
    ]
