# Generated by Django 3.0.5 on 2020-09-10 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0014_auto_20200909_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='archives',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 18, 35, 42, 582831)),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='likes',
        ),
        migrations.AddField(
            model_name='messages',
            name='likes',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
