# Generated by Django 3.0.5 on 2020-09-11 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0015_auto_20200910_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 1, 21, 57, 876284)),
        ),
    ]
