# Generated by Django 3.0.5 on 2020-09-11 11:39

import anon.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0016_auto_20200911_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Letters, digits and underscore only.', max_length=30, unique=True, validators=[anon.models.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 12, 39, 43, 90324)),
        ),
    ]
