# Generated by Django 3.0.5 on 2020-09-11 23:28

import anon.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0017_auto_20200911_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=anon.models.UsernameCapitalizeField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Letters, digits and underscore only.', max_length=30, unique=True, validators=[anon.models.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 0, 28, 20, 723238)),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='telegram_choice',
            field=models.CharField(blank=True, default=3, max_length=1),
        ),
    ]
