# Generated by Django 3.0.5 on 2020-09-14 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0018_auto_20200912_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 11, 39, 10, 689521)),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='telegram_choice',
            field=models.CharField(blank=True, default='3', max_length=1),
        ),
    ]
