# Generated by Django 3.0.5 on 2020-09-16 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0019_auto_20200914_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 12, 49, 16, 583232)),
        ),
    ]
